import Banner from "@/components/Banner";
import Header from "@/components/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#ecf0f1] relative text-gray-700 min-h-screen">
        <Banner />
        <Header />
        {children}
      </body>
    </html>
  );
}
